import { Injectable, signal, computed } from '@angular/core';
import { LanguageType } from '../models/settings.model';

// English Translations
const EN_TRANSLATIONS: Record<string, string> = {
  // Common
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.search': 'Search',
  'common.close': 'Close',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.loading': 'Loading...',
  'common.actions': 'Actions',
  'common.status': 'Status',
  'common.active': 'Active',
  'common.inactive': 'Inactive',
  'common.all': 'All',
  'common.none': 'None',
  'common.optional': 'Optional',
  'common.reset': 'Reset',
  'common.apply': 'Apply',
  'common.export': 'Export',
  'common.import': 'Import',
  'common.print': 'Print',
  'common.total': 'Total',
  'common.subtotal': 'Subtotal',
  'common.discount': 'Discount',
  'common.tax': 'Tax',
  'common.quantity': 'Quantity',
  'common.price': 'Price',
  'common.amount': 'Amount',
  'common.date': 'Date',
  'common.time': 'Time',
  'common.name': 'Name',
  'common.phone': 'Phone',
  'common.email': 'Email',
  'common.address': 'Address',
  'common.notes': 'Notes',
  'common.description': 'Description',
  'common.category': 'Category',
  'common.select': 'Select',
  'common.update': 'Update',
  'common.create': 'Create',
  'common.view': 'View',
  'common.details': 'Details',
  'common.success': 'Success',
  'common.error': 'Error',
  'common.warning': 'Warning',
  'common.info': 'Info',
  'common.confirm': 'Confirm',

  // Navigation
  'nav.home': 'Home',
  'nav.products': 'Products',
  'nav.bills': 'Bills & Reports',
  'nav.customers': 'Customers',
  'nav.users': 'Manage Users',
  'nav.settings': 'Settings',
  'nav.logout': 'Logout',

  // Home / Billing
  'home.title': 'Billing',
  'home.billSummary': 'Bill Summary',
  'home.searchProducts': 'Search products by name, ID, or barcode...',
  'home.cart': 'Cart',
  'home.emptyCart': 'Search and add products to get started',
  'home.clearCart': 'Clear Cart',
  'home.checkout': 'Checkout',
  'home.payNow': 'Pay Now',
  'home.grandTotal': 'Grand Total',
  'home.payment': 'Payment',
  'home.paymentMethod': 'Payment Method',
  'home.cash': 'Cash',
  'home.card': 'Card',
  'home.online': 'Online',
  'home.debt': 'Debt',
  'home.amountReceived': 'Amount Received',
  'home.change': 'Change',
  'home.customerName': 'Customer Name',
  'home.customerPhone': 'Customer Phone',
  'home.addProduct': 'Add Product',
  'home.scan': 'Scan',
  'home.items': 'Items',
  'home.product': 'Product',
  'home.note': 'Note',
  'home.total': 'Total',
  'home.warranty': 'Warranty',
  'home.none': 'None',
  'home.select': 'Select',
  'home.new': 'new',

  // Products
  'products.title': 'Products',
  'products.addProduct': 'Add Product',
  'products.editProduct': 'Edit Product',
  'products.productName': 'Product Name',
  'products.productId': 'Product ID',
  'products.barcode': 'Barcode',
  'products.unitPrice': 'Unit Price',
  'products.costPrice': 'Cost Price',
  'products.stock': 'Stock',
  'products.stockQuantity': 'Stock Quantity',
  'products.lowStockAlert': 'Low Stock Alert',
  'products.searchProducts': 'Search Products',
  'products.noProducts': 'No products found',
  'products.addFirst': 'Add your first product',
  'products.deleteConfirm': 'Are you sure you want to delete this product?',
  'products.warranty': 'Warranty',
  'products.warrantyMonths': 'Warranty (months)',
  'products.looseItem': 'Loose Item',
  'products.unit': 'Unit',
  'products.printBarcode': 'Print Barcode',

  // Bills
  'bills.title': 'Bills & Reports',
  'bills.billNumber': 'Bill Number',
  'bills.billDate': 'Bill Date',
  'bills.dateTime': 'Date & Time',
  'bills.itemsCount': 'Items',
  'bills.paymentStatus': 'Payment Status',
  'bills.paid': 'Paid',
  'bills.pending': 'Pending',
  'bills.partial': 'Partial',
  'bills.today': 'Today',
  'bills.yesterday': 'Yesterday',
  'bills.thisWeek': 'This Week',
  'bills.thisMonth': 'This Month',
  'bills.custom': 'Custom',
  'bills.totalSales': 'Total Sales',
  'bills.totalBills': 'Total Bills',
  'bills.cashSales': 'Cash Sales',
  'bills.cardSales': 'Card Sales',
  'bills.onlineSales': 'Online Sales',
  'bills.cardOnline': 'Card/Online',
  'bills.pendingDebt': 'Pending Debt',
  'bills.debtPaid': 'Debt Paid',
  'bills.debtAmount': 'Debt Amount',
  'bills.totalTax': 'Total Tax',
  'bills.startDate': 'Start Date',
  'bills.endDate': 'End Date',
  'bills.paymentMethod': 'Payment Method',
  'bills.allMethods': 'All Methods',
  'bills.allStatus': 'All Status',
  'bills.downloadReport': 'Download Report',
  'bills.noBills': 'No bills found',
  'bills.filters': 'Filters',
  'bills.table': 'Table',

  // Customers
  'customers.title': 'Customers',
  'customers.addCustomer': 'Add Customer',
  'customers.editCustomer': 'Edit Customer',
  'customers.customerName': 'Customer Name',
  'customers.customerPhone': 'Phone Number',
  'customers.totalDebt': 'Total Debt',
  'customers.noDebt': 'No Debt',
  'customers.searchCustomers': 'Search Customers',
  'customers.noCustomers': 'No customers found',
  'customers.noCustomersYet': 'No customers yet. Add your first customer to get started.',
  'customers.allLoaded': 'All customers loaded',
  'customers.loadingMore': 'Loading more customers...',
  'customers.deleteConfirm': 'Are you sure you want to delete this customer?',

  // Settings
  'settings.title': 'Settings',
  'settings.business': 'Business',
  'settings.account': 'Account',
  'settings.appearance': 'Appearance',
  'settings.tableColumns': 'Table Columns',
  'settings.businessInfo': 'Business Information',
  'settings.businessName': 'Business Name',
  'settings.businessAddress': 'Business Address',
  'settings.businessPhone': 'Phone Number',
  'settings.businessEmail': 'Email Address',
  'settings.logo': 'Business Logo',
  'settings.uploadLogo': 'Upload Logo',
  'settings.changeLogo': 'Change Logo',
  'settings.applicationType': 'Application Type',
  'settings.theme': 'Theme',
  'settings.darkMode': 'Dark Mode',
  'settings.language': 'Language',
  'settings.english': 'English',
  'settings.hindi': 'Hindi',
  'settings.scanner': 'Scanner',
  'settings.scannerType': 'Scanner Type',
  'settings.noScanner': 'No Scanner',
  'settings.cameraScanner': 'Camera Scanner',
  'settings.usbScanner': 'USB Scanner',
  'settings.categories': 'Categories',
  'settings.manageCategories': 'Manage Categories',
  'settings.addCategory': 'Add Category',
  'settings.tax': 'Tax',
  'settings.enableTax': 'Enable Tax',
  'settings.taxRates': 'Tax Rates',
  'settings.discount': 'Discount',
  'settings.enableDiscount': 'Enable Discount',
  'settings.invoice': 'Invoice',
  'settings.invoicePrefix': 'Invoice Prefix',
  'settings.footerText': 'Footer Text',
  'settings.changePassword': 'Change Password',
  'settings.currentPassword': 'Current Password',
  'settings.newPassword': 'New Password',
  'settings.confirmPassword': 'Confirm Password',
  'settings.viewMode': 'View Mode',
  'settings.desktop': 'Desktop',
  'settings.mobile': 'Mobile',
  'settings.manageColumns': 'Manage Table Columns',
  'settings.columnsHint': 'Show or hide columns for different tables',
  'settings.productsTable': 'Products Table',
  'settings.billsTable': 'Bills Table',
  'settings.customersTable': 'Customers Table',
  'settings.resetDefault': 'Reset to Default',
  'settings.savePreferences': 'Save Preferences',
  'settings.saveChanges': 'Save Changes',
  'settings.saving': 'Saving...',
  'settings.accountSettings': 'Account Settings',
  'settings.manageProfile': 'Manage your profile and preferences',
  'settings.profilePhoto': 'Profile Photo',
  'settings.uploadPhoto': 'Upload Photo',
  'settings.changePhoto': 'Change Photo',
  'settings.themeMode': 'Theme Mode',
  'settings.lightMode': 'Light Mode',
  'settings.password': 'Password',
  'settings.passwordHint': 'Change your account password for security',
  'settings.taxConfig': 'Tax Configuration',
  'settings.taxConfigHint': 'Configure tax settings for your bills',
  'settings.taxName': 'Tax Name',
  'settings.taxRate': 'Tax Rate',
  'settings.taxRegNumber': 'Tax Registration Number',
  'settings.enableDebt': 'Enable Debt',
  'settings.receipt': 'Receipt',
  'settings.receiptSettings': 'Receipt Settings',
  'settings.receiptHint': 'Customize your receipt format and content',
  'settings.showLogo': 'Show Logo on Receipt',
  'settings.invoiceStart': 'Invoice Start Number',
  'settings.footerMessage': 'Receipt Footer Message',
  'settings.productCategories': 'Product Categories',
  'settings.categoriesHint': 'Manage product categories for better organization',
  'settings.newCategory': 'New Category Name',
  'settings.currency': 'Currency',
  'settings.barcodeScanner': 'Barcode Scanner',
  'settings.columnsVisible': 'columns visible',
  'settings.scannerNone': 'None',
  'settings.scannerNoneDesc': 'Disable barcode scanning',
  'settings.scannerCamera': 'Device Camera',
  'settings.scannerCameraDesc': 'Use device camera to scan barcodes',
  'settings.scannerUsb': 'USB Scanner',
  'settings.scannerUsbDesc': 'Coming soon - Use USB barcode scanner',
  'settings.comingSoon': 'Coming Soon',
  'settings.unitsManagement': 'Units Management',
  'settings.unitsHint': 'Manage units for loose items like oil, grains, etc.',
  'settings.unitName': 'Unit Name',
  'settings.symbol': 'Symbol',
  'settings.allowDecimal': 'Allow Decimal',
  'settings.decimal': 'Decimal',
  'settings.availableUnits': 'Available Units',
  'settings.businessDetailsHint': 'Your business details for bills and receipts',
  'settings.languageHint': 'Select your preferred language for the application',
  'settings.taxAutoApply': 'Apply tax automatically to all bills',
  'settings.taxRegHint': 'Optional: Will be displayed on receipts',
  'settings.discountHint': 'Show discount input field in bill summary',
  'settings.debtHint': 'Allow debt payment method and manage borrowers',
  'settings.logoHint': 'Display your business logo at the top of receipts',
  'settings.footerHint': 'Displayed at the bottom of the receipt',
  'settings.categoryHint': 'Check categories to make them available in products. General category cannot be removed.',
  'settings.mobileHint': 'Mobile mode: Compact display with truncated IDs and optimized columns for small screens.',
  'settings.desktopHint': 'Desktop mode: Full display with all details visible.',
  'settings.tableParcelMgmt': 'Table / Parcel Management',
  'settings.type': 'Type',
  'settings.dineInTables': 'Dine-In Tables',
  'settings.parcelTakeaway': 'Parcel/Takeaway',
  'settings.from': 'From',
  'settings.to': 'To',
  'settings.parcelNumbers': 'Parcel Numbers',
  'settings.itemNotes': 'Item Notes',
  'settings.noteLabel': 'Note Label',
  'settings.addNote': 'Add Note',

  // Column Labels
  'column.productId': 'Product ID',
  'column.name': 'Name',
  'column.productName': 'Product Name',
  'column.barcode': 'Barcode',
  'column.category': 'Category',
  'column.unitPrice': 'Unit Price',
  'column.stockQuantity': 'Stock',
  'column.status': 'Status',
  'column.actions': 'Actions',
  'column.billNumber': 'Bill Number',
  'column.createdAt': 'Date',
  'column.table': 'Table',
  'column.itemsCount': 'Items',
  'column.grandTotal': 'Total',
  'column.paymentMethod': 'Payment Method',
  'column.paymentStatus': 'Payment Status',
  'column.phone': 'Phone',
  'column.totalDebt': 'Total Debt',

  // Hotel Mode
  'hotel.selectTable': 'Select Table',
  'hotel.dineIn': 'Dine-in Tables',
  'hotel.takeaway': 'Takeaway / Parcel',
  'hotel.changeTable': 'Change Table',
  'hotel.currentTable': 'Current Table',
  'hotel.kot': 'KOT',
  'hotel.printKot': 'Print KOT',
  'hotel.kitchenOrder': 'Kitchen Order Ticket',
  'hotel.sentToKitchen': 'Sent to Kitchen',
  'hotel.note': 'Note',

  // Auth
  'auth.login': 'Login',
  'auth.signIn': 'Sign in to your account',
  'auth.emailOrPhone': 'Email or Phone',
  'auth.enterEmailOrPhone': 'Enter your email or phone',
  'auth.username': 'Username',
  'auth.password': 'Password',
  'auth.enterPassword': 'Enter your password',
  'auth.loginButton': 'Sign In',
  'auth.signingIn': 'Signing In...',
  'auth.forgotPassword': 'Forgot Password?',
  'auth.invalidCredentials': 'Invalid username or password',
  'auth.defaultAdmin': 'Default Admin',

  // Messages
  'msg.saveSuccess': 'Saved successfully',
  'msg.saveFailed': 'Failed to save',
  'msg.deleteSuccess': 'Deleted successfully',
  'msg.deleteFailed': 'Failed to delete',
  'msg.updateSuccess': 'Updated successfully',
  'msg.updateFailed': 'Failed to update',
  'msg.addSuccess': 'Added successfully',
  'msg.addFailed': 'Failed to add',
  'msg.paymentSuccess': 'Payment completed successfully',
  'msg.paymentFailed': 'Payment failed',
  'msg.invalidInput': 'Please check your input',
  'msg.required': 'This field is required',
  'msg.confirmDelete': 'Are you sure you want to delete?',

  // Users
  'users.title': 'Manage Users',
  'users.addUser': 'Add User',
  'users.editUser': 'Edit User',
  'users.searchUsers': 'Search users',
  'users.noUsers': 'No users found',
  'users.createFirst': 'Create First User',
  'users.clearSearch': 'Clear Search',
  'users.role': 'Role',
  'users.lastLogin': 'Last Login',
  'users.never': 'Never',
  'users.resetPassword': 'Reset Password',
  'users.activate': 'Activate',
  'users.deactivate': 'Deactivate',
  'users.admin': 'Admin',
  'users.staff': 'Staff',
  'users.permissions': 'Permissions',
};

// Hindi Translations
const HI_TRANSLATIONS: Record<string, string> = {
  // Common
  'common.save': 'सहेजें',
  'common.cancel': 'रद्द करें',
  'common.delete': 'हटाएं',
  'common.edit': 'संपादित करें',
  'common.add': 'जोड़ें',
  'common.search': 'खोजें',
  'common.close': 'बंद करें',
  'common.yes': 'हाँ',
  'common.no': 'नहीं',
  'common.loading': 'लोड हो रहा है...',
  'common.actions': 'कार्य',
  'common.status': 'स्थिति',
  'common.active': 'सक्रिय',
  'common.inactive': 'निष्क्रिय',
  'common.all': 'सभी',
  'common.none': 'कोई नहीं',
  'common.optional': 'वैकल्पिक',
  'common.reset': 'रीसेट',
  'common.apply': 'लागू करें',
  'common.export': 'निर्यात',
  'common.import': 'आयात',
  'common.print': 'प्रिंट',
  'common.total': 'कुल',
  'common.subtotal': 'उप-योग',
  'common.discount': 'छूट',
  'common.tax': 'कर',
  'common.quantity': 'मात्रा',
  'common.price': 'मूल्य',
  'common.amount': 'राशि',
  'common.date': 'तारीख',
  'common.time': 'समय',
  'common.name': 'नाम',
  'common.phone': 'फ़ोन',
  'common.email': 'ईमेल',
  'common.address': 'पता',
  'common.notes': 'नोट्स',
  'common.description': 'विवरण',
  'common.category': 'श्रेणी',
  'common.select': 'चुनें',
  'common.update': 'अपडेट',
  'common.create': 'बनाएं',
  'common.view': 'देखें',
  'common.details': 'विवरण',
  'common.success': 'सफल',
  'common.error': 'त्रुटि',
  'common.warning': 'चेतावनी',
  'common.info': 'जानकारी',
  'common.confirm': 'पुष्टि करें',

  // Navigation
  'nav.home': 'होम',
  'nav.products': 'उत्पाद',
  'nav.bills': 'बिल और रिपोर्ट',
  'nav.customers': 'ग्राहक',
  'nav.users': 'उपयोगकर्ता प्रबंधन',
  'nav.settings': 'सेटिंग्स',
  'nav.logout': 'लॉग आउट',

  // Home / Billing
  'home.title': 'बिलिंग',
  'home.billSummary': 'बिल सारांश',
  'home.searchProducts': 'नाम, ID, या बारकोड से उत्पाद खोजें...',
  'home.cart': 'कार्ट',
  'home.emptyCart': 'उत्पाद खोजें और जोड़ें',
  'home.clearCart': 'कार्ट खाली करें',
  'home.checkout': 'चेकआउट',
  'home.payNow': 'अभी भुगतान करें',
  'home.grandTotal': 'कुल योग',
  'home.payment': 'भुगतान',
  'home.paymentMethod': 'भुगतान का तरीका',
  'home.cash': 'नकद',
  'home.card': 'कार्ड',
  'home.online': 'ऑनलाइन',
  'home.debt': 'उधार',
  'home.amountReceived': 'प्राप्त राशि',
  'home.change': 'वापसी',
  'home.customerName': 'ग्राहक का नाम',
  'home.customerPhone': 'ग्राहक का फ़ोन',
  'home.addProduct': 'उत्पाद जोड़ें',
  'home.scan': 'स्कैन',
  'home.items': 'आइटम',
  'home.product': 'उत्पाद',
  'home.note': 'नोट',
  'home.total': 'कुल',
  'home.warranty': 'वारंटी',
  'home.none': 'कोई नहीं',
  'home.select': 'चुनें',
  'home.new': 'नया',

  // Products
  'products.title': 'उत्पाद',
  'products.addProduct': 'उत्पाद जोड़ें',
  'products.editProduct': 'उत्पाद संपादित करें',
  'products.productName': 'उत्पाद का नाम',
  'products.productId': 'उत्पाद ID',
  'products.barcode': 'बारकोड',
  'products.unitPrice': 'इकाई मूल्य',
  'products.costPrice': 'लागत मूल्य',
  'products.stock': 'स्टॉक',
  'products.stockQuantity': 'स्टॉक मात्रा',
  'products.lowStockAlert': 'कम स्टॉक अलर्ट',
  'products.searchProducts': 'उत्पाद खोजें',
  'products.noProducts': 'कोई उत्पाद नहीं मिला',
  'products.addFirst': 'अपना पहला उत्पाद जोड़ें',
  'products.deleteConfirm': 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं?',
  'products.warranty': 'वारंटी',
  'products.warrantyMonths': 'वारंटी (महीने)',
  'products.looseItem': 'खुला आइटम',
  'products.unit': 'इकाई',
  'products.printBarcode': 'बारकोड प्रिंट करें',

  // Bills
  'bills.title': 'बिल और रिपोर्ट',
  'bills.billNumber': 'बिल नंबर',
  'bills.billDate': 'बिल की तारीख',
  'bills.dateTime': 'तारीख और समय',
  'bills.itemsCount': 'आइटम',
  'bills.paymentStatus': 'भुगतान की स्थिति',
  'bills.paid': 'भुगतान हुआ',
  'bills.pending': 'बाकी',
  'bills.partial': 'आंशिक',
  'bills.today': 'आज',
  'bills.yesterday': 'कल',
  'bills.thisWeek': 'इस सप्ताह',
  'bills.thisMonth': 'इस महीने',
  'bills.custom': 'कस्टम',
  'bills.totalSales': 'कुल बिक्री',
  'bills.totalBills': 'कुल बिल',
  'bills.cashSales': 'नकद बिक्री',
  'bills.cardSales': 'कार्ड बिक्री',
  'bills.onlineSales': 'ऑनलाइन बिक्री',
  'bills.cardOnline': 'कार्ड/ऑनलाइन',
  'bills.pendingDebt': 'बाकी उधार',
  'bills.debtPaid': 'उधार चुकाया',
  'bills.debtAmount': 'उधार राशि',
  'bills.totalTax': 'कुल कर',
  'bills.startDate': 'प्रारंभ तिथि',
  'bills.endDate': 'अंतिम तिथि',
  'bills.paymentMethod': 'भुगतान का तरीका',
  'bills.allMethods': 'सभी तरीके',
  'bills.allStatus': 'सभी स्थिति',
  'bills.downloadReport': 'रिपोर्ट डाउनलोड करें',
  'bills.noBills': 'कोई बिल नहीं मिला',
  'bills.filters': 'फ़िल्टर',
  'bills.table': 'टेबल',

  // Customers
  'customers.title': 'ग्राहक',
  'customers.addCustomer': 'ग्राहक जोड़ें',
  'customers.editCustomer': 'ग्राहक संपादित करें',
  'customers.customerName': 'ग्राहक का नाम',
  'customers.customerPhone': 'फ़ोन नंबर',
  'customers.totalDebt': 'कुल उधार',
  'customers.noDebt': 'कोई उधार नहीं',
  'customers.searchCustomers': 'ग्राहक खोजें',
  'customers.noCustomers': 'कोई ग्राहक नहीं मिला',
  'customers.noCustomersYet': 'अभी कोई ग्राहक नहीं। शुरू करने के लिए अपना पहला ग्राहक जोड़ें।',
  'customers.allLoaded': 'सभी ग्राहक लोड हो गए',
  'customers.loadingMore': 'और ग्राहक लोड हो रहे हैं...',
  'customers.deleteConfirm': 'क्या आप वाकई इस ग्राहक को हटाना चाहते हैं?',

  // Settings
  'settings.title': 'सेटिंग्स',
  'settings.business': 'व्यवसाय',
  'settings.account': 'खाता',
  'settings.appearance': 'दिखावट',
  'settings.tableColumns': 'टेबल कॉलम',
  'settings.businessInfo': 'व्यवसाय की जानकारी',
  'settings.businessName': 'व्यवसाय का नाम',
  'settings.businessAddress': 'व्यवसाय का पता',
  'settings.businessPhone': 'फ़ोन नंबर',
  'settings.businessEmail': 'ईमेल पता',
  'settings.logo': 'व्यवसाय लोगो',
  'settings.uploadLogo': 'लोगो अपलोड करें',
  'settings.changeLogo': 'लोगो बदलें',
  'settings.applicationType': 'एप्लिकेशन का प्रकार',
  'settings.theme': 'थीम',
  'settings.darkMode': 'डार्क मोड',
  'settings.language': 'भाषा',
  'settings.english': 'अंग्रेज़ी',
  'settings.hindi': 'हिंदी',
  'settings.scanner': 'स्कैनर',
  'settings.scannerType': 'स्कैनर का प्रकार',
  'settings.noScanner': 'कोई स्कैनर नहीं',
  'settings.cameraScanner': 'कैमरा स्कैनर',
  'settings.usbScanner': 'USB स्कैनर',
  'settings.categories': 'श्रेणियाँ',
  'settings.manageCategories': 'श्रेणियाँ प्रबंधित करें',
  'settings.addCategory': 'श्रेणी जोड़ें',
  'settings.tax': 'कर',
  'settings.enableTax': 'कर सक्षम करें',
  'settings.taxRates': 'कर की दरें',
  'settings.discount': 'छूट',
  'settings.enableDiscount': 'छूट सक्षम करें',
  'settings.invoice': 'चालान',
  'settings.invoicePrefix': 'चालान उपसर्ग',
  'settings.footerText': 'फुटर टेक्स्ट',
  'settings.changePassword': 'पासवर्ड बदलें',
  'settings.currentPassword': 'वर्तमान पासवर्ड',
  'settings.newPassword': 'नया पासवर्ड',
  'settings.confirmPassword': 'पासवर्ड की पुष्टि करें',
  'settings.viewMode': 'व्यू मोड',
  'settings.desktop': 'डेस्कटॉप',
  'settings.mobile': 'मोबाइल',
  'settings.manageColumns': 'टेबल कॉलम प्रबंधित करें',
  'settings.columnsHint': 'विभिन्न टेबल के लिए कॉलम दिखाएं या छुपाएं',
  'settings.productsTable': 'उत्पाद टेबल',
  'settings.billsTable': 'बिल टेबल',
  'settings.customersTable': 'ग्राहक टेबल',
  'settings.resetDefault': 'डिफ़ॉल्ट पर रीसेट करें',
  'settings.savePreferences': 'प्राथमिकताएं सहेजें',
  'settings.saveChanges': 'परिवर्तन सहेजें',
  'settings.saving': 'सहेजा जा रहा है...',
  'settings.accountSettings': 'खाता सेटिंग्स',
  'settings.manageProfile': 'अपनी प्रोफ़ाइल और प्राथमिकताएं प्रबंधित करें',
  'settings.profilePhoto': 'प्रोफ़ाइल फोटो',
  'settings.uploadPhoto': 'फोटो अपलोड करें',
  'settings.changePhoto': 'फोटो बदलें',
  'settings.themeMode': 'थीम मोड',
  'settings.lightMode': 'लाइट मोड',
  'settings.password': 'पासवर्ड',
  'settings.passwordHint': 'सुरक्षा के लिए अपना खाता पासवर्ड बदलें',
  'settings.taxConfig': 'कर कॉन्फ़िगरेशन',
  'settings.taxConfigHint': 'अपने बिलों के लिए कर सेटिंग्स कॉन्फ़िगर करें',
  'settings.taxName': 'कर नाम',
  'settings.taxRate': 'कर दर',
  'settings.taxRegNumber': 'कर पंजीकरण नंबर',
  'settings.enableDebt': 'उधार सक्षम करें',
  'settings.receipt': 'रसीद',
  'settings.receiptSettings': 'रसीद सेटिंग्स',
  'settings.receiptHint': 'अपनी रसीद का फॉर्मेट और सामग्री कस्टमाइज़ करें',
  'settings.showLogo': 'रसीद पर लोगो दिखाएं',
  'settings.invoiceStart': 'चालान प्रारंभ नंबर',
  'settings.footerMessage': 'रसीद फुटर संदेश',
  'settings.productCategories': 'उत्पाद श्रेणियाँ',
  'settings.categoriesHint': 'बेहतर संगठन के लिए उत्पाद श्रेणियाँ प्रबंधित करें',
  'settings.newCategory': 'नई श्रेणी का नाम',
  'settings.currency': 'मुद्रा',
  'settings.barcodeScanner': 'बारकोड स्कैनर',
  'settings.columnsVisible': 'कॉलम दिखाई दे रहे हैं',
  'settings.scannerNone': 'कोई नहीं',
  'settings.scannerNoneDesc': 'बारकोड स्कैनिंग अक्षम करें',
  'settings.scannerCamera': 'डिवाइस कैमरा',
  'settings.scannerCameraDesc': 'बारकोड स्कैन करने के लिए डिवाइस कैमरा का उपयोग करें',
  'settings.scannerUsb': 'USB स्कैनर',
  'settings.scannerUsbDesc': 'जल्द आ रहा है - USB बारकोड स्कैनर का उपयोग करें',
  'settings.comingSoon': 'जल्द आ रहा है',
  'settings.unitsManagement': 'इकाई प्रबंधन',
  'settings.unitsHint': 'तेल, अनाज आदि जैसे खुले आइटम के लिए इकाई प्रबंधित करें',
  'settings.unitName': 'इकाई नाम',
  'settings.symbol': 'प्रतीक',
  'settings.allowDecimal': 'दशमलव की अनुमति दें',
  'settings.decimal': 'दशमलव',
  'settings.availableUnits': 'उपलब्ध इकाई',
  'settings.businessDetailsHint': 'बिल और रसीद के लिए आपके व्यवसाय का विवरण',
  'settings.languageHint': 'एप्लिकेशन के लिए अपनी पसंदीदा भाषा चुनें',
  'settings.taxAutoApply': 'सभी बिलों पर स्वचालित रूप से कर लागू करें',
  'settings.taxRegHint': 'वैकल्पिक: रसीद पर प्रदर्शित होगा',
  'settings.discountHint': 'बिल सारांश में छूट इनपुट फ़ील्ड दिखाएं',
  'settings.debtHint': 'उधार भुगतान विधि की अनुमति दें और उधारकर्ताओं का प्रबंधन करें',
  'settings.logoHint': 'रसीद के शीर्ष पर अपना व्यवसाय लोगो प्रदर्शित करें',
  'settings.footerHint': 'रसीद के नीचे प्रदर्शित होगा',
  'settings.categoryHint': 'उत्पादों में उपलब्ध करने के लिए श्रेणियों को चेक करें। सामान्य श्रेणी नहीं हटाई जा सकती।',
  'settings.mobileHint': 'मोबाइल मोड: छोटी स्क्रीन के लिए संक्षिप्त ID और ऑप्टिमाइज़्ड कॉलम के साथ कॉम्पैक्ट डिस्प्ले।',
  'settings.desktopHint': 'डेस्कटॉप मोड: सभी विवरण दिखाई देने वाला पूर्ण डिस्प्ले।',
  'settings.tableParcelMgmt': 'टेबल / पार्सल प्रबंधन',
  'settings.type': 'प्रकार',
  'settings.dineInTables': 'डाइन-इन टेबल',
  'settings.parcelTakeaway': 'पार्सल/टेकअवे',
  'settings.from': 'से',
  'settings.to': 'तक',
  'settings.parcelNumbers': 'पार्सल नंबर',
  'settings.itemNotes': 'आइटम नोट्स',
  'settings.noteLabel': 'नोट लेबल',
  'settings.addNote': 'नोट जोड़ें',

  // Column Labels
  'column.productId': 'उत्पाद ID',
  'column.name': 'नाम',
  'column.productName': 'उत्पाद का नाम',
  'column.barcode': 'बारकोड',
  'column.category': 'श्रेणी',
  'column.unitPrice': 'इकाई मूल्य',
  'column.stockQuantity': 'स्टॉक',
  'column.status': 'स्थिति',
  'column.actions': 'कार्य',
  'column.billNumber': 'बिल नंबर',
  'column.createdAt': 'तारीख',
  'column.table': 'टेबल',
  'column.itemsCount': 'आइटम',
  'column.grandTotal': 'कुल',
  'column.paymentMethod': 'भुगतान का तरीका',
  'column.paymentStatus': 'भुगतान की स्थिति',
  'column.phone': 'फ़ोन',
  'column.totalDebt': 'कुल उधार',

  // Hotel Mode
  'hotel.selectTable': 'टेबल चुनें',
  'hotel.dineIn': 'डाइन-इन टेबल',
  'hotel.takeaway': 'टेकअवे / पार्सल',
  'hotel.changeTable': 'टेबल बदलें',
  'hotel.currentTable': 'वर्तमान टेबल',
  'hotel.kot': 'KOT',
  'hotel.printKot': 'KOT प्रिंट करें',
  'hotel.kitchenOrder': 'किचन ऑर्डर टिकट',
  'hotel.sentToKitchen': 'किचन को भेजा गया',
  'hotel.note': 'नोट',

  // Auth
  'auth.login': 'लॉग इन',
  'auth.signIn': 'अपने खाते में साइन इन करें',
  'auth.emailOrPhone': 'ईमेल या फ़ोन',
  'auth.enterEmailOrPhone': 'अपना ईमेल या फ़ोन दर्ज करें',
  'auth.username': 'उपयोगकर्ता नाम',
  'auth.password': 'पासवर्ड',
  'auth.enterPassword': 'अपना पासवर्ड दर्ज करें',
  'auth.loginButton': 'साइन इन करें',
  'auth.signingIn': 'साइन इन हो रहा है...',
  'auth.forgotPassword': 'पासवर्ड भूल गए?',
  'auth.invalidCredentials': 'अमान्य उपयोगकर्ता नाम या पासवर्ड',
  'auth.defaultAdmin': 'डिफ़ॉल्ट एडमिन',

  // Messages
  'msg.saveSuccess': 'सफलतापूर्वक सहेजा गया',
  'msg.saveFailed': 'सहेजने में विफल',
  'msg.deleteSuccess': 'सफलतापूर्वक हटाया गया',
  'msg.deleteFailed': 'हटाने में विफल',
  'msg.updateSuccess': 'सफलतापूर्वक अपडेट किया गया',
  'msg.updateFailed': 'अपडेट करने में विफल',
  'msg.addSuccess': 'सफलतापूर्वक जोड़ा गया',
  'msg.addFailed': 'जोड़ने में विफल',
  'msg.paymentSuccess': 'भुगतान सफलतापूर्वक पूरा हुआ',
  'msg.paymentFailed': 'भुगतान विफल',
  'msg.invalidInput': 'कृपया अपना इनपुट जांचें',
  'msg.required': 'यह फ़ील्ड आवश्यक है',
  'msg.confirmDelete': 'क्या आप वाकई हटाना चाहते हैं?',

  // Users
  'users.title': 'उपयोगकर्ता प्रबंधन',
  'users.addUser': 'उपयोगकर्ता जोड़ें',
  'users.editUser': 'उपयोगकर्ता संपादित करें',
  'users.searchUsers': 'उपयोगकर्ता खोजें',
  'users.noUsers': 'कोई उपयोगकर्ता नहीं मिला',
  'users.createFirst': 'पहला उपयोगकर्ता बनाएं',
  'users.clearSearch': 'खोज साफ़ करें',
  'users.role': 'भूमिका',
  'users.lastLogin': 'अंतिम लॉगिन',
  'users.never': 'कभी नहीं',
  'users.resetPassword': 'पासवर्ड रीसेट करें',
  'users.activate': 'सक्रिय करें',
  'users.deactivate': 'निष्क्रिय करें',
  'users.admin': 'एडमिन',
  'users.staff': 'स्टाफ',
  'users.permissions': 'अनुमतियां',
};

const TRANSLATIONS: Record<LanguageType, Record<string, string>> = {
  'en': EN_TRANSLATIONS,
  'hi': HI_TRANSLATIONS
};

@Injectable({
  providedIn: 'root'
})
export class TranslateService {
  private currentLang = signal<LanguageType>('en');
  
  // Computed translations based on current language
  translations = computed(() => TRANSLATIONS[this.currentLang()]);

  get language(): LanguageType {
    return this.currentLang();
  }

  setLanguage(lang: LanguageType): void {
    this.currentLang.set(lang);
    // Store in localStorage for persistence
    localStorage.setItem('billwise_language', lang);
  }

  initLanguage(lang?: LanguageType): void {
    // Priority: Passed lang > localStorage > default 'en'
    const storedLang = localStorage.getItem('billwise_language') as LanguageType | null;
    const finalLang = lang || storedLang || 'en';
    this.currentLang.set(finalLang);
  }

  /**
   * Translate a key to the current language
   * @param key Translation key (e.g., 'common.save')
   * @param fallback Optional fallback text if key not found
   * @returns Translated string
   */
  t(key: string, fallback?: string): string {
    const translation = this.translations()[key];
    if (translation) {
      return translation;
    }
    // Try English as fallback
    if (this.currentLang() !== 'en' && EN_TRANSLATIONS[key]) {
      return EN_TRANSLATIONS[key];
    }
    // Return fallback or key itself
    return fallback || key;
  }

  /**
   * Get all translations for the current language
   */
  getAllTranslations(): Record<string, string> {
    return this.translations();
  }
}
